export const ERRORS = {
  INCORRECT_PASS: 'INCORRECT_PASSWORD',
  ID_UNDEFINED: 'ID_UNDEFINED',
  NOT_FOUND: 'ENTITY_NOT_FOUND',
  USER: {
    EXIST: 'USER_EXIST',
    NOT_EXIST: 'USER_NOT_EXIST'
  }
};

export const MESSAGES = {
  USER: {
    LOGINED: 'USER_LOGINED',
    CREATED: 'USER_CREATED'
  }
};
